### ISSUE TITLE
bug: Setting message_limit less than 25 in ChannelList props disables infinite scroll functionality

### ISSUE THREAD

**Issue by Milad-Mohamadi** [GetStream/stream-chat-react#2360] opened 2024-04-09 12:59 UTC
**Describe the bug**

When configuring the ChannelList component with a message_limit value of less than 25, the "load more messages" functionality appears to be non-functional. This issue occurs even though the expected behavior is for the infinite scroll to work with any specified message_limit.

**To Reproduce**

1. Environment Setup: Ensure you are using the latest version of stream-chat-react. This can be confirmed by checking the package version in your package.json file or by running npm list stream-chat-react or yarn list stream-chat-react in your project directory.

2. Component Configuration: Implement the ChannelList component within your React application with initial properties set for watchers, filters, options, and custom components like so: 
`<ChannelList
  watchers={{ limit: 10 }}
  filters={{ type: 'messaging', members: { $in: ['user-id'] }}}
  options={{ limit: 10, message_limit: 25 }}
  channelRenderFilterFn={channels => channels.filter(channel => channel.type === 'messaging')}
  Preview={CustomChannelPreview}
  Paginator={InfiniteScroll}
  LoadingIndicator={UnMemoizedLoadingChannels}
/>
`
Replace 'user-id' with a valid user ID from your application.

3. Adjust message_limit: Change the message_limit value within the options prop to a value less than 25, for example:
`options={{ limit: 10, message_limit: 20 }}
`
4. Start the Application: Run your React application and navigate to the page or component where the ChannelList is rendered.
5. Observe the Initial Load: Verify that the initial set of messages loads according to the specified message_limit.
6. Attempt to Scroll: Try scrolling through the message list to trigger additional messages to load.
7. Identify the Issue: Notice that despite reaching the end of the currently loaded messages, no additional messages are loaded regardless of the total number of messages available in the channel.

**Expected behavior**
The infinite scroll feature should work regardless of the message_limit value, allowing users to load more messages as they scroll.

**Actual  behavior**
When the message_limit is set to a value less than 25, the infinite scroll functionality seems to be disabled, preventing more messages from being loaded.

**Package version**
- stream-chat: ^8.11.0
- stream-chat-react: ^10.10.1

**Desktop:**
- OS: macOS 14.4.1 (23E224)
- Browser: Chrome
- Version: 123.0.6312.107

**Comment by myandrienko** [comment] 2024-04-09 14:08
Hi @Milad-Mohamadi, thanks for the report!

I can see that you are using v10 of our React SDK. The latest version is v11.14.0. We [fixed](https://github.com/GetStream/stream-chat-react/pull/2292) the issue you're describing in the v11 branch not that long ago, so please upgrade and see if the issue is fixed for you.

Upgrade from v10 to v11 should be painless, however if you run into any difficulties, please refer to our [upgrade guide](https://getstream.io/chat/docs/sdk/react/release-guides/upgrade-to-v11/).

I'm going to close this issue for now.

**Closed by myandrienko** 2024-04-09 14:08 UTC
Labels: bug, status: unconfirmed

**Comment by Milad-Mohamadi** [comment] 2024-04-09 21:13
Thank you @myandrienko  for the quick response! I'll upgrade to v11.14.0 and see if that solves the issue. Will let you know how it goes. Appreciate the help!
