### ISSUE TITLE
bug: sending a message larger than 5000 characters as a start of a thread results in an error. 

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1558] opened 2022-04-29 11:49 UTC
**Describe the bug**

A message over 5000 characters as an initial reply in a thread results in the wrong state.

**To Reproduce**

1. Go to https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv?file=/src/App.tsx
2. Send a message
3. Open a thread reply to it - should be a new thread.
4. Send a message with more than 5000 characters.

Rather than displaying the "The message you are trying to send is larger than 5000 characters", the message is stuck in sending state. There's also a `replies` request that returns 400. 

**Expected behavior**

An error message should be presented (red, with the correct wording). 

**Screenshots**

<img width="420" alt="image" src="https://user-images.githubusercontent.com/13347/165938651-abe21788-938f-4842-8e76-752dc4e3d3d9.png">

**Comment by arnautov-anton** [comment] 2022-09-07 21:32
Retried in the latest version, can't reproduce anymore, closing for now.

**Closed by arnautov-anton** 2022-09-07 21:32 UTC
Labels: bug
