### ISSUE TITLE
bug: Super expression must either be null or a function error

### ISSUE THREAD

**Issue by gimurpe** [GetStream/stream-chat-react#1655] opened 2022-06-29 22:48 UTC
**Describe the bug**

Getting "TypeError: Super expression must either be null or a function" after upgrading to version 7.0.0
**To Reproduce**

1. Upgrade stream-chat-react to version 7.0.0

**Expected behavior**

No error is displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/7089148/176558206-1462965e-6818-4a40-ab83-e6ae341346ef.png)

**Package version**
- stream-chat-react: 7.0.0
- stream-chat-js: 6.7.2

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [chrome]

**Smartphone (please complete the following information):**

- Browser [chrome]
- Version [103.0.5060.53 (Official Build) (x86_64)]

**Additional context**

issue also occurred with version 9.1.4 , issue only occurs in production mode

**Comment by petyosi** [comment] 2022-06-30 05:35
Hi @gimurpe , 

this is not a known issue. we will need additional information to reproduce the problem since it is likely related to additional customizations on your side. Can you replicate the problem by modifying [this sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv?file=/src/App.tsx)? You can also contact us at support@getstream.io if the reproduction is specific to your account or data.

**Comment by gimurpe** [comment] 2022-06-30 14:54
@petyosi I found this is related to react-image-gallery introduced in version 7.0.0 : https://github.com/xiaolin/react-image-gallery/issues/624 .

**Comment by superCoderDOM** [comment] 2022-07-13 14:08
@petyosi We are having the exact same issue. The error does not show on a development build, but as soon as we build for production, react won't even load due to this error.

**Comment by petyosi** [comment] 2022-07-14 04:47
@superCoderDOM how can we reproduce the problem on our side? Is this related to the image gallery from above?

**Comment by arnautov-anton** [comment] 2022-09-07 21:50
Can't reproduce, no reply from the issue author, closing for now.

**Closed by arnautov-anton** 2022-09-07 21:50 UTC
Labels: bug, status: unconfirmed

**Comment by opengeekslabap** [comment] 2022-11-22 14:06
same issue @arnautov-anton 
![Screenshot 2022-11-22 at 16 06 04](https://user-images.githubusercontent.com/57400666/203334196-bbf4a903-e051-4b5a-b921-d144d977e49f.png)

**Comment by opengeekslabap** [comment] 2022-11-22 20:27
@gimurpe fixed:
problem is:
after webpack minification package of stream-chat-react -> `react-image-gallery` was broken.
solution: 

disable optimization **minimizer** for `react-image-gallery` 
craco.config.js or webpack.config:

```js

const applySplitChunks = (webpackConfig) => {
  webpackConfig.optimization.splitChunks = {
    chunks: 'all',
    maxInitialRequests: Infinity,
    minSize: 0,
    // https://stackoverflow.com/a/52961891
    cacheGroups: {
      vendor: {
        test: /[\\/]node_modules[\\/](react-image-gallery)[\\/]/,
        name(module) {
          const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
          return `npm.${packageName.replace('@', '')}`;
        },
      },
    },
  }

}

const applyOptimizationFilter = (webpackConfig) => {
  const skipMinimizationForChunk = [
    'npm.react-image-gallery'
  ]
  const terser = webpackConfig.optimization.minimizer.find(item => item.options.terserOptions);
  terser.options.chunkFilter = (chunk) => {
    return !skipMinimizationForChunk.includes(chunk.name);
  }
}

module.exports = {
  webpack: {
    configure(webpackConfig) {
     ...
      applySplitChunks(webpackConfig)
      applyOptimizationFilter(webpackConfig)
      return webpackConfig;
    }
```
![Screenshot 2022-11-22 at 22 26 25](https://user-images.githubusercontent.com/57400666/203414392-7693901f-bbdc-4442-b586-0b322a447549.png)

`craco build`
`serve -s build`

**Comment by gabrielfurini** [comment] 2024-01-10 18:10
I'm getting this error when using React Native with Expo (latest SDK - 49) as well. 😢 
Is there any way to fix it or workaround?

**Comment by arnautov-anton** [comment] 2024-01-11 10:17
Hey, @gabrielfurini - would you be able to share with us some sort of a repository with reproduction steps? Expo is no longer officially supported with this package (for that we have this [`stream-chat-expo`](https://www.npmjs.com/package/stream-chat-expo) package) but we could try and take a look if you can provide said repository.

**Comment by gabrielfurini** [comment] 2024-01-11 14:16
@arnautov-anton My mistake. The error was related to the [stream-video-js](https://github.com/GetStream/stream-video-js) package. The error message is the same, by the way. There is already a issue opened there: https://github.com/GetStream/stream-video-js/issues/1231
