### ISSUE TITLE
ChannelList error after delete/leave channel

### ISSUE THREAD

**Issue by kovacsmarcellcodinglab** [GetStream/stream-chat-react#185] opened 2020-03-26 16:28 UTC
Hi,

I got this error after I delete  or memeber leave the channel:
Uncaught (in promise) TypeError: Cannot set property 'data' of undefined.

channelIndex (-1) cause the error in ChannelList component:

                if (e.type === 'channel.updated') {
                  channels = _this.state.channels;
                  channelIndex = channels.findIndex(function (channel) {
                    return channel.cid === e.channel.cid;
                  });
                  channels[channelIndex].data = Immutable(e.channel); <-- error line

![kép](https://user-images.githubusercontent.com/60096424/77670948-29c0f100-6f87-11ea-8bc6-ef55f5d123e0.png)

![kép](https://user-images.githubusercontent.com/60096424/77670967-30e7ff00-6f87-11ea-94ce-1daee5adc9cc.png)

channelIndex = -1, not check this case

After when I got this error ChannelList component is down and not working any more.

Pls help how to solve this issue asap.

Thx
Marcell

**Comment by vishalnarkhede** [comment] 2020-03-26 16:44
Hey @kovacsmarcellcodinglab thanks for bringing this up. I will fix this asap today :)

**Comment by kovacsmarcellcodinglab** [comment] 2020-03-27 09:56
Hi,

I think your changes its not good, because if you do not set state, the component freeze.
We need to use condition like this, not just return:

if (channelIndex >= 0) {
 channels[channelIndex].data = Immutable(e.channel);
}

Event Update and Delete too.

Thx
Marcell

**Comment by kovacsmarcellcodinglab** [comment] 2020-03-27 10:16
Hi,

I test it. And works only if you use this fix:

- Update:
`if (e.type === 'channel.updated') {
                  channels = _this.state.channels;
                  channelIndex = channels.findIndex(function (channel) {
                    return channel.cid === e.channel.cid;
                  });

                  if (channelIndex >= 0) {
                    channels[channelIndex].data = Immutable(e.channel);
                  }
                  
                  _this.setState({
                    channels: _toConsumableArray(channels),
                    channelUpdateCount: _this.state.channelUpdateCount + 1
                  });

                  if (_this.props.onChannelUpdated && typeof _this.props.onChannelUpdated === 'function') {
                    _this.props.onChannelUpdated(_assertThisInitialized(_this), e);
                  }
                }`

- Delete
` if (e.type === 'channel.deleted') {
                  if (_this.props.onChannelDeleted && typeof _this.props.onChannelDeleted === 'function') {
                    _this.props.onChannelDeleted(_assertThisInitialized(_this), e);
                  } else {
                    _channels = _this.state.channels;
                    _channelIndex = _channels.findIndex(function (channel) {
                      return channel.cid === e.channel.cid;
                    }); // Remove the deleted channel from the list.s

                    if (_channelIndex >= 0) {
                      _channels.splice(_channelIndex, 1);
                    }

                    _this.setState({
                      channels: _toConsumableArray(_channels),
                      channelUpdateCount: _this.state.channelUpdateCount + 1
                    });
                  }
                }`

**Comment by vishalnarkhede** [comment] 2020-03-27 10:37
> if you do not set state, the component freeze.

What do you mean by this? You can't interact with channellist anymore?

**Comment by kovacsmarcellcodinglab** [comment] 2020-03-27 11:09
Hi,

> What do you mean by this? You can't interact with channellist anymore?
Yes, If you add only condition with return ChannelList is not working anymore.

If you use condition like me, ChannelList is working well.

Thx
Marcell

**Comment by vishalnarkhede** [comment] 2020-03-27 12:40
@kovacsmarcellcodinglab I don't see a reason why component should freeze though. And I am not able to reproduce this unfortunatel. Can you please share some code around the way you are using ChannelList component?

**Comment by kovacsmarcellcodinglab** [comment] 2020-03-27 12:53
I use Chat components like this:
` <Chat client={this.chatClient} theme={"messaging light"}>
                                <ChannelList
                                    List={ChannelListMessenger}
                                    Preview={FriendChannelPreviewConst}
                                    filters={filters}
                                    sort={sort}
                                    options={options}
                                    setActiveChannelOnMount={true}
                                />
                            <Channel>
                                <Window>
                                    <FriendChannelHeader
                                        user={this.state.user}
/>
                                    <div className="str-chat__main-panel">
                                        <MessageList messageActions={["edit", "delete"]} TypingIndicator={TypingIndicator} />
                                        <MessageInput Input={MessageInputSmall} focus />
                                    </div>
                                </Window>
                            </Channel>
                        </Chat>`

I use own Preview:
        const FriendChannelPreviewConst = ({ setActiveChannel, channel, unread, latestMessage, activeChannel, watchers, active, latestMessageLength }) => (
            <FriendChannelPreview
                chatClient={this.chatClient}
                deleteGroup={this.deleteGroup}
                removeFromGroup={this.removeFromGroup}
                setActiveChannel={setActiveChannel}
                channel={channel}
                unread={unread}
                latestMessage={latestMessage}
                activeChannel={activeChannel}
                watchers={watchers}
                active={active}
                latestMessageLength={latestMessageLength}
            />
        );

I remove member from channel like this:
async removeFromGroup(channel, activeChannel, setActiveChannel) {
       
        let name = channel.data.name;
        name = name.replace(this.state.user.name.toString() + ",", "");
        name = name.replace(", " + this.state.user.name.toString(), "");
        name = name.replace(this.state.user.name.toString(), "");
        name = name.trim();

        await channel.removeMembers([this.state.user.accountId.toString()]);
        await channel.stopWatching();
        await channel.update(
            {
                name: name,
            },
            { text: this.state.user.name + " leave the group chat" }
        );
    }

I delete channel like this:
async deleteGroup(channel, activeChannel, setActiveChannel) {

        let arrMembers = Object.values(channel.state.members);
        arrMembers = arrMembers.map(f => f.user.id);

        await channel.removeMembers(arrMembers);
        await channel.stopWatching();
        await channel.delete();
    }

Thx
Marcell

**Comment by vishalnarkhede** [comment] 2020-03-27 14:31
Hey @kovacsmarcellcodinglab 

Couple of suggestions:

```diff
async removeFromGroup(channel, activeChannel, setActiveChannel) {
        let name = channel.data.name;
        name = name.replace(this.state.user.name.toString() + ",", "");
        name = name.replace(", " + this.state.user.name.toString(), "");
        name = name.replace(this.state.user.name.toString(), "");
        name = name.trim();
+        await channel.removeMembers([this.state.user.accountId.toString()], {
+           text: this.state.user.name + " leave the group chat"
+        });
-        await channel.removeMembers([this.state.user.accountId.toString()]);
-        await channel.stopWatching();
-        await channel.update(
-            {
-               name: name,
-           },
-            { text: this.state.user.name + " leave the group chat" }
-        );
    }
```

```diff
async deleteGroup(channel, activeChannel, setActiveChannel) {
    let arrMembers = Object.values(channel.state.members);
    arrMembers = arrMembers.map(f => f.user.id);

-    await channel.removeMembers(arrMembers);
-    await channel.stopWatching();
     await channel.delete();
}
```

I am not still sure why you are running into freeze issue. Can you please try suggested changes and let me know if they help? :)

**Comment by kovacsmarcellcodinglab** [comment] 2020-03-27 15:38
Hi,


I still get the error, if I use this way.

Thx
Marcell

**Comment by vishalnarkhede** [comment] 2020-03-27 17:40
@kovacsmarcellcodinglab what error did you get this time?

**Comment by kovacsmarcellcodinglab** [comment] 2020-03-27 19:07
Hi,

The same, If I use your actual version with your suggestion:
channelIndex (-1) cause the error in ChannelList component:

            if (e.type === 'channel.updated') {
              channels = _this.state.channels;
              channelIndex = channels.findIndex(function (channel) {
                return channel.cid === e.channel.cid;
              });
              channels[channelIndex].data = Immutable(e.channel); <-- error line

![kép](https://user-images.githubusercontent.com/60096424/77789944-3c5d2800-7064-11ea-8a91-923763f000ce.png)

![kép](https://user-images.githubusercontent.com/60096424/77789971-45e69000-7064-11ea-9d3d-435de072772f.png)

If I use your new code and with your suggestion, the component will not working well anymore (freeze).

Pls. fix it with my code suggestion and create a new release, because we need a working getstream solution.

Thx
Marcell

**Comment by vishalnarkhede** [comment] 2020-03-29 18:26
Hey @kovacsmarcellcodinglab , I understand your situation and I want to get this resolved as soon as possible as well. But I can't make the change blindly without knowing the root cause of problem. Currently I see no reason why the component should freeze if you don't call setState. 

But you can unblock yourself meanwhile. You can pass following prop functions to override event handlers and thus to force update the state of component:

- onChannelUpdated
- onChannelDeleted

```js
<ChannelList
    onChannelUpdated={(channelListComponent, event) => {
        // Force update the state, as required by your app.
        channelListComponent.setState({
          channels: [...channelListComponent.state.channels],
          channelUpdateCount: channelListComponent.state.channelUpdateCount + 1,
        });
    }}
    onChannelDeleted={(channelListComponent, event) => {
        const channels = channelListComponent.state.channels;
        const channelIndex = channels.findIndex(
          (channel) => channel.cid === e.channel.cid,
        );

        if (channelIndex >= 0) {
            // Remove the deleted channel from the list.s
            channels.splice(channelIndex, 1);
        }

        // Force update the state, as required by your app.
        channelListComponent.setState({
          channels: [...channels],
          channelUpdateCount: channelListComponent.state.channelUpdateCount + 1,
        });
    }}
    filters={filters}
    sort={sort}
    options={options}
/>
```

Let me know if this helps :)

**Comment by kovacsmarcellcodinglab** [comment] 2020-03-30 15:04
Hi, 

I updated latest version and working well, so I not need any additional code right now.

Thx
Marcell

**Comment by vishalnarkhede** [comment] 2020-03-30 20:28
Thats a good news @kovacsmarcellcodinglab . I am gonna close this issue now.

**Closed by vishalnarkhede** 2020-03-30 20:28 UTC
