### ISSUE TITLE
ChannelHeader menu button gone on mobile

### ISSUE THREAD

**Issue by rumfiske** [GetStream/stream-chat-react#1593] opened 2022-05-16 19:55 UTC
**Describe the bug**
The burger menu button is gone on mobile

**To Reproduce**

i use Next.js and have just used the component <ChannelHeader/>

**Screenshots**
https://i.imgur.com/fXuSkYR.png
Image of the button from a desktop resized window. Here you can see it, from a real mobile device its gone. I tested with 2 iphones 12, and 1 Samsung,

**Package version**
- stream-chat-react: 8.1.2

**Comment by MartinCupela** [comment] 2022-05-17 07:52
@rumfiske I have tried to run the `examples/nextjs`, `examples/typescript` app on my Samsung mobile and was able to see the icon. Browsers used were Safari and Chrome? Could you please attach screenshots from your phones?

**Comment by petyosi** [comment] 2022-05-19 06:01
@MartinCupela I reproduce this in desktop Safari on MacOS, using this sample: https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv. It looks like the SVG icon does not size correctly (see screenshot). I fiddled with adding explicit sizing (i.e. `width: 200px`) and it fixed it, but probably there's a more robust and correct way to fix it. 

<img width="660" alt="image" src="https://user-images.githubusercontent.com/13347/169220446-9cbbb6b1-4cd5-4095-91fd-fdfa7b21dae6.png">

**Comment by MartinCupela** [comment] 2022-09-13 08:30
fixed with the release of v10.0.0

**Closed by MartinCupela** 2022-09-13 08:30 UTC
Labels: bug, status:confirmed
