### ISSUE TITLE
Check if User already Registered | Friends handling | Username Validation

### ISSUE THREAD

**Issue by mobeendev** [GetStream/stream-chat-react#943] opened 2021-05-26 07:57 UTC
is there any way to check if the user already registered or not?
And what would you suggest about handling user's friends list i.e should we handle on our BE DB or we just query for user presence on your server!
Also, what are the restrictions on username i.e can we use special characters, etc.

**Comment by DanC5** [comment] 2021-05-26 14:01
@mobeendev Thanks for reaching out and we’re happy to see you getting your hands on the product. However, the Issue section of this Github repo is reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we suggest emailing our Customer Success and engineering support team at support@getstream.io. Include your application key or ID and SDK version number and we’ll be able to help you out. Thanks for your understanding and I'm going to close this issue so you can continue the conversation with support.

In case our understanding is incorrect and you are describing a bug, we apologize, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.

**Closed by DanC5** 2021-05-26 14:01 UTC
