### ISSUE TITLE
bug: HEIC file can not render from S3

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2215] opened 2023-12-13 17:18 UTC
**Describe the bug**

Before uploading the file, I use the MessageInput component doImageUploadRequest to upload the file to s3, then retrieve the file with the url, then I press enter and send the attachment, you can view the image. But with the HEIC file, it can't be rendered.

![Screenshot 2023-12-14 at 12 02 49 AM](https://github.com/GetStream/stream-chat-react/assets/17897146/3e8b54c9-e1b1-4c08-b5db-333ffb5a73d5)

**To Reproduce**

1. Create s3 server receive file and return file url
2. Before upload at MessageInput, attachment the file and receive url from s3 (HEIC file)
3. Enter
4. Can not render

**Expected behavior**

Render a HEIC file as an image, like a png or jpg.

**Screenshots**

https://github.com/GetStream/stream-chat-react/assets/17897146/ffacda66-b43d-4842-a3b4-a2a75ea237d6

**Package version**
- stream-chat-react: 11.1.1
- stream-chat-css: 4.1.0
- stream-chat-js: 8.14.4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arnautov-anton** [comment] 2023-12-13 23:39
Hey, @minhth-1529, HEIC files cannot be rendered through `img` element as it's [not supported](https://caniuse.com/?search=HEIC) by the most browsers, see #2182 for more information.

**Comment by MartinCupela** [comment] 2023-12-14 08:28
@minhth-1529 could you please share the file that failed to be loaded? HEIC files are supported but depends on encoding. I see that GitHub for example does not support HEIC, but on the other hand, I am pretty sure that [this HEIC file](https://us-east.stream-io-cdn.com/1145265/images/b558713b-b4ff-4620-befc-5b61fbee510c.dwsample-heic-640.heic?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy1lYXN0LnN0cmVhbS1pby1jZG4uY29tLzExNDUyNjUvaW1hZ2VzL2I1NTg3MTNiLWI0ZmYtNDYyMC1iZWZjLTViNjFmYmVlNTEwYy5kd3NhbXBsZS1oZWljLTY0MC5oZWljPypvaD00Mjgqb3c9NjQwKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMzY5MTM2MX19fV19&Signature=hf-86eUJKlGM3T-LN0H2jRezxQO4t8mVVGTIKbFXg8NPugQE38KmFwUVpUeI8AVmTyccmHhWBUxmp8xuSQxtC4Fk3yJzu3LunF9BWzjsebdyI3SL6r744v1FgPLjDMywUypDrnIIH5a9laGwRKLWqskxPNN0XH2cUTLCLR1TM5mzjkPkg0I7zBPBpeaERol4dHEyUsqL6PbeLyTgAgn6oI50~etOmrA~856gE2-8WtrHKsPhV-UHkSWK~KUM9sJI-xW0xgZlwHl3XgHBzYN94hqpjNjpJCykK3uaDPHevoDvMRoqRor0LGd-1cFdlBRbVrPHrl6f~KXce1IAs4R4uQ__&oh=428&ow=640) should work with the SDK. 

Could you please try to post the file in the link below to check, whether it fails? If not, then the problem is in your file which probably will not be rendered in any other messenger app (also please check).

Could you please share the link to the file that files to load on your side?

**Comment by minhth-1529** [comment] 2023-12-15 07:48
Hi @MartinCupela Any file HEIC file upload follow my step on video, it can not render.

Here https://drive.google.com/drive/folders/1zI6XwaO9CvaqUH0JriDNR-owJBDVSy-p?usp=sharing

**Comment by Phu96** [comment] 2023-12-15 08:22
> @minhth-1529 could you please share the file that failed to be loaded? HEIC files are supported but depends on encoding. I see that GitHub for example does not support HEIC, but on the other hand, I am pretty sure that [this HEIC file](https://us-east.stream-io-cdn.com/1145265/images/b558713b-b4ff-4620-befc-5b61fbee510c.dwsample-heic-640.heic?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy1lYXN0LnN0cmVhbS1pby1jZG4uY29tLzExNDUyNjUvaW1hZ2VzL2I1NTg3MTNiLWI0ZmYtNDYyMC1iZWZjLTViNjFmYmVlNTEwYy5kd3NhbXBsZS1oZWljLTY0MC5oZWljPypvaD00Mjgqb3c9NjQwKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMzY5MTM2MX19fV19&Signature=hf-86eUJKlGM3T-LN0H2jRezxQO4t8mVVGTIKbFXg8NPugQE38KmFwUVpUeI8AVmTyccmHhWBUxmp8xuSQxtC4Fk3yJzu3LunF9BWzjsebdyI3SL6r744v1FgPLjDMywUypDrnIIH5a9laGwRKLWqskxPNN0XH2cUTLCLR1TM5mzjkPkg0I7zBPBpeaERol4dHEyUsqL6PbeLyTgAgn6oI50~etOmrA~856gE2-8WtrHKsPhV-UHkSWK~KUM9sJI-xW0xgZlwHl3XgHBzYN94hqpjNjpJCykK3uaDPHevoDvMRoqRor0LGd-1cFdlBRbVrPHrl6f~KXce1IAs4R4uQ__&oh=428&ow=640) should work with the SDK.
> 
> Could you please try to post the file in the link below to check, whether it fails? If not, then the problem is in your file which probably will not be rendered in any other messenger app (also please check).
> 
> Could you please share the link to the file that files to load on your side?

actually your heic image has content type image/jpeg encoding, therefore it can be rendered, moreover your heic image is from getstream CDN, i think they convert the heic to jpg when receiving the heic image from the backend.

**Comment by MartinCupela** [comment] 2023-12-15 08:23
@minhth-1529 have you tested also with the file I have provided and confirmed it gets correctly rendered on my side? If the browser downloads the image but throws an error on image loading then the problem will be with the image not the SDK. The SDK reacts to the error event emitted by the browser.

> i think they convert the heic to jpg when receiving the heic image from the backend.

The file is correctly rendered in attachment preview list - so before sending it to the backend.

**Comment by Phu96** [comment] 2023-12-15 08:33
> @minhth-1529 have you tested also with the file I have provided and confirmed it gets correctly rendered on my side? If the browser downloads the image but throws an error on image loading then the problem will be with the image not the SDK. The SDK reacts to the error event emitted by the browser.
> 
> > i think they convert the heic to jpg when receiving the heic image from the backend.
> 
> The file is correctly rendered in attachment preview list - so before sending it to the backend.

actually no, i've checked with the real HEIC image, which was not rendered correctly in the attachment preview list. I'm certain that the HEIC image is not corrupted. The mentioned image is here [https://dev-fim.storage.fastboy.dev/5c190e09-4389-43e4-a876-94553bcb0376cb0f4557-cb74-4bfa-8b78-14a0d7ffa866de5b7d2d-88fe-4af1-bd11-a36012c9004e7be489d3-449b-4398-bcca-14c7fb5cdcdf.heic](url). You can download it then try to convert the image from this website https://cloudconvert.com/heic-to-jpg

**Comment by MartinCupela** [comment] 2023-12-15 08:43
Ok guys, let me sum this up:

1. The HEIC file I used locally for testing does render correctly - there is no doubt
2. The browser determines, whether error event is emitted when rendering an image with `<img/>` element - our SDK component just reacts to that event and shows the fallback

Is there a browser app that does render your image without throwing an error?

**Comment by Phu96** [comment] 2023-12-15 08:51
> Ok guys, let me sum this up:
> 
> 1. The HEIC file I used locally for testing does render correctly - there is no doubt
> 2. The browser determines, whether error event is emitted when rendering an image with `<img/>` element - our SDK component just reacts to that event and shows the fallback
> 
> Is there a browser app that does render your image without throwing an error?

Thank you for your patience. But for this problem, I think you've tried to upload the HEIC file to Getstream CDN, which will convert the HEIC file to JPG from their CDN backend. The image ended up rendering correctly in the attachment preview list because it had been uploaded to the Getstream CDN before rendering in the UI. 

In order to reproduce this issue, we must use a custom CDN to upload instead.

**Comment by MartinCupela** [comment] 2023-12-15 09:09
Confirmed that the preview image is jpeg. Apologies for that mistake.

Still my point about browser determining, whether the load error event is emitted, is valid.

At the end @arnautov-anton will be right about browsers not supporting HEIC - at least according to [CAN I USE](https://caniuse.com/?search=HEIC).

Is there app running in your browser that is able to render the HEIC img?

**Comment by MartinCupela** [comment] 2023-12-18 12:20
@Phu96 @minhth-1529 I would close this issue as it really seems, there is not good browser support for this file type.

**Closed by MartinCupela** 2023-12-18 12:20 UTC
Labels: bug, status: unconfirmed
