### ISSUE TITLE
Unexpected behavior using customClasses prop of Chat component

### ISSUE THREAD

**Issue by aargondizza** [GetStream/stream-chat-react#1212] opened 2021-09-30 04:55 UTC
If I structure my chat app component tree like this:

```tsx
      <Chat client={client} customClasses={customClasses}>
        <Channel channel={channel.current}>
          <MessageList />
          <MessageInput />
        </Channel>
      </Chat>
```

And I define my custom classes like this:

```tsx
const customClasses: CustomClasses = {
  chat: chatStyle,
  channel: channelStyle,
  messageList: messageListStyle,
};
```

The resulting styled `<div>`s on the DOM put this pesky `str-chat__container` in between `<Channel>` and its children:

![image](https://user-images.githubusercontent.com/911729/135387199-f58454fd-f6d9-4226-ab15-d77117525e2d.png)

I'd expect to be able to style `<Channel>` with `display: flex; flex-direction: row;` and have the `<MessageList>` and `<MessageInput>` lay out next to each other left-to-right, but this doesn't work because I'm actually just applying `flex` to the one container `<div>`.

I've worked around this by wrapping `<MessageList>` and `<MessageInput>` in my own container:

```tsx
      <Chat client={client} customClasses={customClasses}>
        <Channel channel={channel.current}>
          <MessagingContainer>
            <MessageList />
            <MessageInput />
          </MessagingContainer>
        </Channel>
      </Chat>
```

but there are still some things I can't do to my `<MessagingContainer>` because I can't style its parent:

![image](https://user-images.githubusercontent.com/911729/135389364-a32d4cd4-e6ec-44c8-8d82-dbfd17565fe1.png)

I could definitely be wrong - maybe there's a way to do all of what I want with that container in between - but it feels a bit unintuitive given the structure of the React components and the classes available via the `customClasses` prop.

For now I'm just overriding the `str-chat__container` class name globally without using the `customClasses` prop.

Thanks for taking a look at this!

**Comment by DanC5** [comment] 2021-09-30 14:54
Hey @aargondizza thanks for providing such solid detail. So if I understand you correctly, you just need a way to pass your own custom class to replace `str-chat__container`? That's not a problem if so, we can easily add a new `chatContainer` key to the `customClasses` object that replaces this class name.

**Comment by DanC5** [comment] 2021-09-30 19:33
@aargondizza we just added this additional custom CSS class to the object mapping, https://github.com/GetStream/stream-chat-react/blob/master/src/components/Channel/Channel.tsx#L820.

Let me know if you have additional questions or requests about this, but I'm going to close the issue for now. Expect a release tomorrow, 10/1. Thanks!

**Closed by DanC5** 2021-09-30 19:33 UTC

**Comment by aargondizza** [comment] 2021-09-30 20:08
Thanks! I think this is similar to the workaround I created and certainly helps but still feels a little unintuitive.

I'm probably simplifying the logic quite a bit here, but I think how I would expect this to work is:

`if (customClasses.channel) { /* don't use the str-chat__container container div */ }`

because if I'm using React components like this:

```tsx
      <Chat client={client} customClasses={customClasses}>
        <Channel channel={channel}>
          <MessageList />
          <MessageInput />
        </Channel>
      </Chat>
```

it feels odd to me to have to define styles for a container I can't see in my component tree, i.e. this:

```tsx
const customClasses: CustomClasses = {
  chat: chatStyle,
  channel: channelStyle,
  chatContainer: chatContainerStyle,
  messageList: messageListStyle,
};
```

Instead I'd expect each field of the customClasses object to map _directly_ to a component in my component tree.

Looking at it again, it's also a bit strange to me to have the `chatClass` and `channelClass` be applied to the same div for similar reasons:

https://github.com/GetStream/stream-chat-react/blob/135623fe8b6178c435b1e087488656390e94fcf4/src/components/Channel/Channel.tsx#L851-L865

I think I would do something like this:

```tsx
return (
  <div className={`${chatClass} ${theme} ${windowsEmojiClass}`}>
    <div className={channelClass}>
      <ChannelStateProvider value={channelStateContextValue}>
        <ChannelActionProvider value={channelActionContextValue}>
          <ComponentProvider value={componentContextValue}>
            <EmojiProvider value={emojiContextValue}>
              <TypingProvider value={typingContextValue}>
                {children}
              </TypingProvider>
            </EmojiProvider>
          </ComponentProvider>
        </ChannelActionProvider>
      </ChannelStateProvider>
    </div>
  </div>
);
```

in which case we wouldn't need `chatContainer` in `customClasses` at all. If the container serves a purpose though, maybe you could conditionally remove it only if `customClasses?.channel` is defined.

The general point here is that if we think of `<MessageList>` and `<MessageInput>` as the children, in the component tree I'm working with, `<Channel>` is already their style-able parent container.

**Comment by DanC5** [comment] 2021-09-30 20:16
@aargondizza this makes sense and actually follows a similar train of though we had recently. Part of the issue is the existing CSS structure has been in the library for a couple years now, so we're hesitant to make changes that impact the DOM tree.

The custom class name feature was a bit of a compromise to give some clients that need to override the container stylings a bit of flexibility without adding breaking changes for the rest of our clients. Though I do agree that the tree you shared is the optimal structure, but we're not quite ready to make that kind of a change.

We are looking to make a major release in the coming month or so to reorganize and simplify how we've implemented our TypeScript generics. I'll run this thought by our SDK manager and see if he's interested in making this kind of change as part of that major version release. Breaking CSS changes are always a bit annoying, so I can't say for sure that we'll take this on, but we will give it a look because you're totally right on the optimal structure here.

Thanks!

**Comment by aargondizza** [comment] 2021-09-30 20:31
@DanC5 Awesome, makes sense. Thanks for the consideration and the tweak! While you're at it, I'd love to be able to style `MessageInput` through `customClasses` too... 😅

**Comment by DanC5** [comment] 2021-09-30 20:35
@aargondizza no problem! We actually didn't add any for the `MessageInput` component because we're not enforcing any container styles on that component and all of our defaults are nested within the `MessageInputFlat` Input UI component. So if you add your own Input UI component, which most of our clients do, you don't have to override/unset anything existing from the higher level context provider component.

**Comment by aargondizza** [comment] 2021-10-01 17:14
Thanks for this! https://github.com/GetStream/stream-chat-react/releases/tag/v6.9.1

**Comment by DanC5** [comment] 2021-10-01 17:31
@aargondizza of course! And we'll make a decision on the DOM tree shakeup within the coming month or so
