### ISSUE TITLE
bug: When import 'stream-chat-react/dist/css/index.css'; I end up with 47 warnings ENOENT.... 

### ISSUE THREAD

**Issue by TheHumanistX** [GetStream/stream-chat-react#1973] opened 2023-03-14 20:21 UTC
**Describe the bug**

Imported the CSS file, stream-chat-react/dist/css/index.css.  When I did that I suddenly had 47 warnings. ENOENTs.  I removed the import to verify and had no warnings, added the import back... 47 warnings.  It is looking in V1 locations for files.  

**To Reproduce**

1. added `import 'stream-chat-react/dist/css/index.css';` to my App.js
2. saved/compiled
3. 47 warnings

**Expected behavior**

Should not have warnings?

**Screenshots**

![image](https://user-images.githubusercontent.com/42555733/225126114-afbf3932-ebba-476e-99d8-5725fc5a2a0c.png)
Same errors over and over... Pointing in the wrong place for many items.

**Package version**
- stream-chat-react: ^10.7.2
- stream-chat-css: v2
- stream-chat-js: ^8.4.1

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser [e.g. chrome, safari]: Any

**Comment by arnautov-anton** [comment] 2023-03-14 21:21
Duplicate of #1540.

**Closed by arnautov-anton** 2023-03-14 21:21 UTC
Labels: bug, status: unconfirmed
