### ISSUE TITLE
Chrome display error message on mouseWheel event

### ISSUE THREAD

**Issue by PaulBouisset** [GetStream/stream-chat-react#948] opened 2021-05-27 11:41 UTC
Hi,

On chrome I keep getting the same error message when I scroll inside the MessageList:
`Unable to preventDefault inside passive event listener invocation.`

This is caused by the mousewheelListener in the InfiniteScroll component -> [here](https://github.com/GetStream/stream-chat-react/blob/0a06b91d755738628dc4e7bb0bf8b9151930b614/src/components/InfiniteScrollPaginator/InfiniteScroll.tsx#L120)

Do you know how I could prevent this error to show up? 

From what I understand in the code I can pass options for the infiniteScroll component with `internalInfiniteScrollProps` but the only one I could pass would be "useCapture" and that can only be a boolean. I can't pass other options like `{passive:false}` to prevent the error to show up.

**Comment by yetieaterxb1** [comment] 2021-06-01 14:38
Hi @PaulBouisset,

Thanks for bringing this to our attention. 

I am struggling to reproduce this, but will continue testing and make changes needed to prevent this error. 

-Grant

**Comment by yetieaterxb1** [comment] 2021-06-16 15:29
@PaulBouisset we made a few changes to this event listener in our latest release.  The first is changing the deprecated mousewheel event to wheel. The second change is to add the passive option and set it to false. Although we couldn't reproduce your error, it does seem like a widespread issue with Chrome and the solution is turning off passiveness for wheel events. 

Here is the PR for the changes made https://github.com/GetStream/stream-chat-react/pull/980. 

Thanks for bringing this to our attention. I'm going to close this ticket but please reach back out if this issue persists after upgrading.

Best,
-Grant

**Closed by yetieaterxb1** 2021-06-16 15:29 UTC
