### ISSUE TITLE
bug: Message only shows it has been deleted after refreshing page or deleting twice

### ISSUE THREAD

**Issue by devlukedreamstage** [GetStream/stream-chat-react#1828] opened 2022-10-27 23:25 UTC
**Describe the bug**

When I delete a message that uses my CustomMessage component, I have to delete it twice for it to delete or refresh the page. I don't think the message is being rerendered.

Works fine with the MessageSimple message

**To Reproduce**

Click on menu -> delete message. 

**Expected behavior**

Message should say "This message has been deleted" upon deleting it the first time

**Screenshots**

**Package version**
- stream-chat-react: 9.5.1
- stream-chat: 7.1.0 

**Desktop (please complete the following information):**

- OS: windows
- Browser: Chrome

**Code

# Chat page
```
export default function ShowChat({ title, slug, user }) {
  const chatClient = StreamChat.getInstance(apiKey);
  const isSmallScreen = useMedia(480);

  const [channel, setChannel] = useState(null);
  useEffect(() => {
    (async () => {
      if (user?.id) {
        const res = await fetch(`/api/chat?userId=${user?.id}`);
        const data = await res.json();

        await chatClient.connectUser(
          {
            name: user?.attributes?.chat?.name ?? user?.name ?? user?.email,
            id: user?.id,
          },
          data.token
        );
      } else {
        await chatClient.connectAnonymousUser();
      }

      const channel = chatClient.channel("livestream", slug, {
        name: title,
      });
      await channel.create();
      if (user?.id && !channel.state.members[user.id])
        await channel.addMembers([user.id]);
      await channel.watch();
      setChannel(channel);
    })();

    return () => {
      //    chatClient.disconnectUser().then(() => console.log("disconnected"));
    };
  }, [user]);


  return (
      <Chat client={chatClient}>
        <Channel channel={channel}>
          <Window>
            <Divider />
            <CustomChannelHeader />
            <Divider />
            <VirtualizedMessageList Message={CustomMessage} />
            <MessageInput Input={MessageInputSmall} focus disabled={!user} />
          </Window>
        </Channel>
      </Chat>
  );
}
```

# CustomMessage component

```
function CustomMessage() {
  const {
    isReactionEnabled,
    message,
    reactionSelectorRef,
    showDetailedReactions,
  } = useMessageContext();

  const messageWrapperRef = useRef(null);
  const hasReactions = messageHasReactions(message);
  const hasAttachments = message.attachments && message.attachments.length > 0;
  const [hover, setHover] = useState(false);
  return (
    <Box
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      sx={{
        ".message-wrapper": {
          padding: "5px",
          backgroundColor: "blackAlpha.400",
          ".str-chat__message-simple__actions": {
            position: "absolute",
            // top: "-14px",
            right: "20px",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            height: "24px",
            borderRadius: "100px",
            background: "white",
            border: "1px solid #e0e0e0",
            boxShadow: "0 2px 1px 0 rgba(0, 0, 0, 0.07)",
            zIndex: "1",
            padding: "0 4px 0",

            ".str-chat__message-actions-box--open": {
              left: "-90px",
              borderRadius: "5px",
            },

            "&__action--reactions": {
              display: "flex",
            },

            "&__action--options": {
              display: "flex",
            },

            "&__action--thread": {
              display: "flex",
            },
          },
        },

        ".str-chat__message-text-inner": {
          position: "relative",
          flex: 1,

          color: "black",
          border: 0,
          background: "none",

          p: {
            fontFamily: "Helvetica Neue, sans-serif",
            fontSize: "12px",
            lineHeight: "18px",
            color: "var(--chakra-colors-textPrimary)",
            marginBottom: 0,
          },
        },

        ".str-chat__simple-reactions-list": {
          borderRadius: "10px",
        },

        ".str-chat__reaction-selector": {
          maxHeight: "40px",
          top: "-58px",
          right: "20px",
          borderRadius: "20px",
          background: "white",
          boxShadow: "0 3px 8px rgba(0, 0, 0, 0.15)",
          border: "1px solid #bed5e4",
        },

        ".str-chat__message-reactions-list-item__count": {
          color: "#000000",
        },
      }}
    >
      <div className="message-wrapper">
        <div className="message-wrapper-content">
          {hover && <MessageOptions messageWrapperRef={messageWrapperRef} />}
          {showDetailedReactions && isReactionEnabled && (
            <ReactionSelector ref={reactionSelectorRef} />
          )}
          <Flex align="baseline">
            <Text
              fontWeight={500}
              fontSize="12px"
              lineHeight="120%"
            >
              {message.user?.name}:
            </Text>
            <MessageText />
          </Flex>
          <MessageStatus />
        </div>
      </div>
    </Box>
  );
}
```

**Comment by MartinCupela** [comment] 2022-10-28 07:05
Hello @devlukedreamstage , could you please share a minimal reproduction in codesandbox please? Most probably this will be caused by custom changes that your implementation introduces. Thank you

**Comment by devlukedreamstage** [comment] 2022-10-28 15:39
@MartinCupela https://hbw2f9.csb.app/

Got it to replicate!

**Comment by MartinCupela** [comment] 2022-11-10 11:51
@devlukedreamstage you need to check, whether a message was marked as deleted. If you include the following snippet in your custom message component, the UI is updated accordingly:

```
  if (message.deleted_at || message.type === 'deleted') {
    return <MessageDeleted message={message} />;
  }
```

**Closed by MartinCupela** 2022-11-10 11:51 UTC
Labels: question
