### ISSUE TITLE
Pasting long messages to <MessageInput> does not respect maxLength

### ISSUE THREAD

**Issue by satellink** [GetStream/stream-chat-react#668] opened 2021-01-13 08:43 UTC
Hello!

I am using a <MessageInput /> component in the following way:

```
<MessageInput Input={CommentInput} />

...

const CommentInput = props => {
  const messageInput = useMessageInput(props)
  ... 
  return <ChatAutoComplete additionalTextareaProps={{ maxLength: 280 }} onPaste={messageInput.onPaste} onChange={messageInput.onChange} />
}
```

- When writing a message manually to the field, it works as it should. The input just stops accepting characters after limit has reached
- However when **pasting** a longer text, the text does not get cut to 280 chars

I believe this happens because an implementation of `messageInput.onPaste` does not respect maxLength:

https://github.com/GetStream/stream-chat-react/blob/d9bf06f17eb405e4f7fb8a6211ce2b913cd35d47/src/components/MessageInput/hooks/messageInput.js#L670

gz#8594

**Comment by DanC5** [comment] 2021-01-13 15:25
@satellink I just tested this out and I'm not able to reproduce. In the sample app I'm running adding the additionalTextareaProps always clips the pasted text at the maxLength limit. Here's the before an after of my test, added a maxLength of 50 for the second message. Could you provide screenshots or a video of what you're seeing?

<img width="991" alt="Screen Shot 2021-01-13 at 8 23 30 AM" src="https://user-images.githubusercontent.com/43552931/104471944-aa81c580-5578-11eb-90db-967f9829f67b.png">

**Comment by DanC5** [comment] 2021-01-13 18:56
@satellink Funny thing, I updated Chrome to the latest version, and as you said, it no longer works as expected. Interesting that the textarea html element performs differently across different versions of Chrome, but anyways, I'll work on a fix.

**Comment by DanC5** [comment] 2021-01-13 23:39
@satellink Just put in PR to fix this issue. As soon as we get it merged we'll make a new release, likely on Friday. So for now I'm going to close the issue. Please let us know if you have additional questions, and thanks for noticing this change.
https://github.com/GetStream/stream-chat-react/pull/670

**Closed by DanC5** 2021-01-13 23:39 UTC

**Comment by satellink** [comment] 2021-01-14 07:02
Oh, interesting! I also have Firefox and Brave (on OS X) I've tested with, so I didn't put much thought on the possibility that there can be much difference on behaviour between browsers or browser versions...

Thank you for the future fix!
