### ISSUE TITLE
Send button is invisible

### ISSUE THREAD

**Issue by tmoran-stenoa** [GetStream/stream-chat-react#1094] opened 2021-08-03 23:53 UTC
In a [recent commit](https://github.com/GetStream/stream-chat-react/commit/069202366e88ce5ffa5239826d031b7246901847), the send button was made to render conditionally. I believe there might have been a typo in the condition for it, which is currently `numberOfUploads && !text`. Should it instead be `numberOfUploads || text` ?

[Link to the line in question.](https://github.com/GetStream/stream-chat-react/blob/6f35920a9986e444a3993d24e6c05dfc021304eb/src/components/MessageInput/UploadsPreview.tsx#L58)

As it currently stands, the send button is invisible when text is typed in.

**Comment by DanC5** [comment] 2021-08-04 01:15
Hello @tmoran-stenoa, this actually is the intended behavior. Prior to this addition, if a user added an attachment without any text, they would have had to focus the input and hit enter. Now, if there's an upload but no text, instead of having to focus the input, you can now hit the send button. For non-mobile breakpoints, our default `SendButton`, which is used within the MessageInput UI component (`MessageInputFlat`), hides the send button in its CSS. Though looking at this I did just notice a tweak that needs to be made for mobile breakpoints, which I'll roll out later this week.

https://github.com/GetStream/stream-chat-react/blob/master/src/styles/SendButton.scss#L6

If you wish, you can override this behavior by passing your own `SendButton` as a prop to the `Channel` component (which trickles into the MessageInput) or by overwriting the default CSS. And of course, you could go fully custom by designing your own Input UI component.

https://getstream.io/chat/docs/sdk/react/message-input-components/input_ui/

I'm going to close this address as hopefully it addresses your comment, but do feel free to keep the conversation going as you need. Thanks!

**Closed by DanC5** 2021-08-04 01:15 UTC

**Comment by tmoran-stenoa** [comment] 2021-08-04 18:48
I see. Thank you for the detailed response!
