### ISSUE TITLE
/~/stream-chat-react/dist/assets/str-chat__reaction-list-sprite@1x.png Module parse failed: /Users/akshay/forked_ta-react/node_modules/stream-chat-react/dist/assets/str-chat__reaction-list-sprite@1x.png Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by Aksh0377** [GetStream/stream-chat-react#177] opened 2020-03-25 08:50 UTC

**Comment by vishalnarkhede** [comment] 2020-03-25 12:16
Hey @Aksh0377, can you please give a bit more details about it?

**Comment by Aksh0377** [comment] 2020-03-25 12:27
Hi @vishalnarkhede,

I am using    
"react": "^15.6.2",
node: 6.10.3
using npm for package management.


- installed getstream-chat-react using npm,
  after installing package when i run the project it give the following error:

ERROR in ./~/stream-chat-react/dist/assets/str-chat__reaction-list-sprite@3x.png
Module parse failed: /Users/akshay/forked_ta-react/node_modules/stream-chat-react/dist/assets/str-chat__reaction-list-sprite@3x.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/stream-chat-react/dist/css/index.css 6:78470-78528
 @ ./~/stream-chat-react/dist/css/index.css
 @ ./js-src/components/Chat/Chat.js
 @ ./js-src/routes/routes.js
 @ ./js-src/main.js
 @ multi babel-polyfill ./js-src/main.js

ERROR in ./~/stream-chat-react/dist/index.es.js
Module not found: Error: Can't resolve 'i18next' in '/Users/akshay/forked_ta-react/node_modules/stream-chat-react/dist'
 @ ./~/stream-chat-react/dist/index.es.js 6:0-27
 @ ./js-src/components/Chat/Chat.js
 @ ./js-src/routes/routes.js
 @ ./js-src/main.js
 @ multi babel-polyfill ./js-src/main.js

**Comment by vishalnarkhede** [comment] 2020-03-26 13:45
Hey @Aksh0377 
> ERROR in .//stream-chat-react/dist/index.es.js
Module not found: Error: Can't resolve 'i18next' in '/Users/akshay/forked_ta-react/node_modules/stream-chat-react/dist'

 ↑ This has been resolved in stream-chat-react@0.10.2

> ERROR in .//stream-chat-react/dist/assets/str-chat__reaction-list-sprite@3x.png
Module parse failed: /Users/akshay/forked_ta-react/node_modules/stream-chat-react/dist/assets/str-chat__reaction-list-sprite@3x.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
@ .//css-loader!.//stream-chat-react/dist/css/index.css 6:78470-78528
@ .//stream-chat-react/dist/css/index.css
@ ./js-src/components/Chat/Chat.js
@ ./js-src/routes/routes.js
@ ./js-src/main.js
@ multi babel-polyfill ./js-src/main.js

@jaapbakker88 do you know what this could be about? I tried to setup the sample using npm, and couldn't reproduce this. So its nothing to do with npm or yarn I suppose.

**Comment by vishalnarkhede** [comment] 2020-03-26 13:51
@Aksh0377 can you tell me version of react-node and react-scripts that you are using? I used the latest once in my sample app where it uses latest webpack version.

**Comment by jaapbakker88** [comment] 2020-03-26 15:49
I think the problem is the version of node and react you're using.

We support node versions 10, 11, 12 and 13, and React version 16

**Closed** 2020-04-22 12:08 UTC
