### ISSUE TITLE
bug: Error when clicking on an audio element in a threaded reply (loadMessageIntoState is not a function)

### ISSUE THREAD

**Issue by tkrevh** [GetStream/stream-chat-react#1619] opened 2022-06-09 06:28 UTC
**Describe the bug**

When replying in a thread to a message containing only an audio recording, the reply contains the audio element, but it's not playable. Console says:

```
Uncaught (in promise) TypeError: d.state.loadMessageIntoState is not a function
    at stream-chat-react:formatted:54949:37
    at stream-chat-react:formatted:173:35
    at Object.next (stream-chat-react:formatted:186:18)
    at stream-chat-react:formatted:91:41
    at new Promise (<anonymous>)
    at u (stream-chat-react:formatted:68:16)
    at pe (stream-chat-react:formatted:54940:20)
    at onClick (stream-chat-react:formatted:39885:24)
```

**To Reproduce**

1. Post an audio message to the channel
2. The other chat member should reply in a thread
3. The audio in the thread is not playable, as it results in the error in the console

**Expected behavior**

Audio should be played, same as if one would click on the original audio message.
Or at least it should scroll to the original message.

**Screenshots**

![2022-06-09 08_20_40-screenshot](https://user-images.githubusercontent.com/5480798/172779373-fbed268c-a9ff-428c-8cb1-f027bfe4be04.png)

**Package version**
- stream-chat-react: latest (https://cdn.jsdelivr.net/npm/stream-chat-react)
- stream-chat-css: latest
- stream-chat-js: latest (https://cdn.jsdelivr.net/npm/stream-chat)

**Desktop (please complete the following information):**

Not relevant

**Smartphone (please complete the following information):**

Not relevant

**Additional context**

**Comment by MartinCupela** [comment] 2022-06-09 19:12
@tkrevh I have tried to follow the 3 steps you described for reproduction. Could you please confirm I followed them correctly as I have not experienced any errors playing audio in the main message list neither in the thread?

Please see the video attached:

https://ctrlv.tv/0VMi

**Comment by arnautov-anton** [comment] 2022-09-07 21:28
Closing due to no reply from the author of the issue.

**Closed by arnautov-anton** 2022-09-07 21:28 UTC
Labels: bug, status: unconfirmed
