### ISSUE TITLE
bug: Chat screen is empty after tap on "scroll down" button

### ISSUE THREAD

**Issue by MrMole96** [GetStream/stream-chat-react#2469] opened 2024-08-13 10:13 UTC
**Describe the bug**

Chat doesn't show any content when we tap "scroll bottom" button while scrolling (in motion)

**Expected behavior**

Chat should show content after tapping button

**Screenshots**

**Package version**
- stream-chat-react: 11.23.0

**Smartphone (please complete the following information):**

- OS: iOS

**Additional context**

https://github.com/user-attachments/assets/f73c2f25-ec7c-4ea9-b8e4-01ff913abea7

**Comment by MartinCupela** [comment] 2024-08-21 11:06
@MrMole96 I could not reproduce the behavior where after tapping the ScrollToBottomButton, the message list would be rendered blank. I have tested this with the basic vite application from `examples` folder and used both `MessageList` and `VirtualizedMessageList` on iPhone with iOS 17.5.1 as well as on MacOS 14.5. Feel free to fork [this sandbox](https://codesandbox.io/p/devbox/priceless-forest-g64slj) to demonstrate your setup.

**Comment by MartinCupela** [comment] 2024-09-23 07:50
@MrMole96 is this issue still relevant or can we close it?

**Comment by MartinCupela** [comment] 2024-09-26 09:01
Closing for inactivity

**Closed by MartinCupela** 2024-09-26 09:01 UTC
Labels: bug, status: unconfirmed, pending-reply
